# Generated by Django 2.0.1 on 2020-07-25 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tractebel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitcenter',
            name='businessline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tractebel.BusinessLine'),
        ),
        migrations.AddField(
            model_name='profitcenter',
            name='description',
            field=models.CharField(default='New Profit Center', max_length=50, unique=True),
        ),
    ]
