# Generated by Django 2.0.1 on 2020-07-25 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tractebel', '0003_auto_20200725_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, unique=True)),
                ('businessline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tractebel.BusinessLine')),
                ('profitcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tractebel.ProfitCenter')),
            ],
            options={
                'ordering': ['businessline', 'profitcenter', 'description'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('businessline', 'profitcenter', 'description')},
        ),
    ]
